radhatam/radhatam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('radhatamapp.urls')),
]

radhatam/radhatamapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'radhatamapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('dataingestion/<str:action>/<int:id>', views.dataingestion, name='dataingestion'),
    path('datapreparation/<str:action>/<int:id>', views.datapreparation, name='datapreparation'),
    path('edit_fieldtype/<int:id>', views.edit_fieldtype, name='edit_fieldtype'),

    path('dataviz/<str:action>/<int:id>', views.dataviz, name='dataviz'),
    path('dataalerts/<str:action>/<int:id>', views.dataalerts, name='dataalerts'),


    path('fieldfunction/<str:action>/<int:id>', views.fieldfunction, name='fieldfunction'),

    
]

radhatam/radhatamapp/models.py
from django.db import models
from datetime import date
# Create your models here.
DATA_TYPES = (
    ('TEXT', 'Text'),
    ('INTEGER', 'Integer'),
    ('NUMERIC', 'Numeric'),
    ('DATE', 'Date'),
    ('BINARY', 'Binary'),
    ('PNG_IMAGE', 'PNG Image'),

)

FIELD_TYPES = (
    ('COLUMN', 'Column'),
    ('DERIVED', 'Derived'),
    ('CALCULATED', 'Calculated'),

)

FUNCTION_TYPES = (
    ('CALCULATION', 'Calculation'),
    ('VISUALIZE', 'Visualize'),
    ('DATASCIENCE', 'DataScience'),
    ('GENERATED','Generated'),
)

OP_TYPES = (
    ('eq', 'Exact'),
    ('not', 'Not'),
    ('gt','Greater Than'),
    ('gte','Greater Than Equal To'),
    ('lt','Less Than'),
    ('lte','Less Than Equal'),

)


SQL_OP_TYPES = {'exact': '=', 'not': '!=','gt':'>','gte':'>=','lt':'<','lte':'<='}



class Entity(models.Model):
    name = models.CharField(max_length=30, unique=True)
    # child = models.ForeignKey('self',on_delete=models.DO_NOTHING,null=True)

    def __str__(self):
        return self.name


class FunctionMeta(models.Model):
    name = models.CharField(max_length=30)
    type = models.CharField(
        max_length=20, choices=FUNCTION_TYPES, default='CALCULATION')
    return_type = models.CharField(
        max_length=20, choices=DATA_TYPES, default='TEXT')
    
    function_code = models.TextField()
    return_sql = models.TextField(max_length=1024)   

    def __str__(self):
        return self.name


class ArgumentMeta(models.Model):
    function = models.ForeignKey(
        FunctionMeta, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=30)
    type = models.CharField(max_length=20, choices=DATA_TYPES, default='TEXT')

    def __str__(self):
        return self.name


class Field(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, null=True)
    actual_name = models.CharField(max_length=64)
    name = models.CharField(max_length=64,unique=True)
    main = models.BooleanField(default=False)
    datatype = models.CharField(max_length=64, choices=DATA_TYPES, default='TEXT')
    type = models.CharField(max_length=64, choices=FIELD_TYPES, default='COLUMN')
    child_entity_id = models.IntegerField(null=True)
    child_field_id = models.IntegerField(null=True)
    derived_level = models.IntegerField(default=0)
    function = models.ForeignKey(
        FunctionMeta, on_delete=models.CASCADE, null=True)
    # order = models.IntegerField()

    def __str__(self):
        return self.name



class FieldFilter(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, null=False)
    filter_col = models.CharField(max_length=30, null=False)
    filter_op = models.CharField(
        max_length=30, null=False, choices=OP_TYPES, default='EXACT')
    filter_val = models.CharField(max_length=120, null=False)

    def __str__(self):
        return self.entity.name + " " + self.filter_op


class DerivedFieldArgument(models.Model):
    field = models.ForeignKey(Field, on_delete=models.CASCADE, null=True)
    argument_name = models.CharField(max_length=30, null=True)
    argument_value = models.TextField(null=True)
    argument_type = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.id) + " " + self.field.name + " -> " + self.argument_name + " " + self.argument_value + " " + self.argument_type


class DataScienceTraining(models.Model):
    last_run = models.DateTimeField()
    model_name = models.BinaryField()

radhatam/radhatamapp/forms.py
from django import forms

class UploadFileForm(forms.Form):
    name = forms.CharField(max_length=50)
    csv_file = forms.FileField()

class UploadFileDataForm(forms.Form):   
    csv_file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class DerivedColumnForm(forms.Form):
    name = forms.CharField(max_length=50)

radhatam/radhatamapp/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, HttpResponse
from django.contrib import messages
from .forms import UploadFileForm, UploadFileDataForm, DerivedColumnForm
import pandas as pd
import pygwalker as pyg
from io import StringIO
import logging
from .models import Entity, Field, DATA_TYPES, SQL_OP_TYPES, FunctionMeta, ArgumentMeta, DerivedFieldArgument, FieldFilter
from django.db import connection
from django.conf import settings
import psycopg2
from sqlalchemy import create_engine
from django.contrib import messages

logger = logging.getLogger(__name__)
# Create your views here.

PG_NAME = settings.DATABASES['default']['NAME']
PG_USER = settings.DATABASES['default']['USER']
PG_PWD = settings.DATABASES['default']['PASSWORD']
PG_HOST = settings.DATABASES['default']['HOST']
PG_PORT  = settings.DATABASES['default']['PORT']


conn = psycopg2.connect(dbname=PG_NAME, user=PG_USER, password=PG_PWD,host=PG_HOST,port=PG_PORT)
engine = create_engine(f"postgresql+psycopg2://{PG_USER}:{PG_PWD}@{PG_HOST}/{PG_NAME}")

# sql = "with cte_0 as ( select scripname, market, outlook, growwportfolio_file_name, pe, code, low, close, last, prevclose, no_trades, no_of_shrs, sc_name, net_turnov, sc_group, sc_type, tdcloindi, bhavcopy_file_name, sc_code, open, high from growwportfolio left join bhavcopy on growwportfolio.code = bhavcopy.sc_code ), cte_1 as ( select *, convert_str_to_date(bhavcopy_file_name) as trade_date from cte_0), cte_2 as ( select *, avg(close) over(partition by code order by trade_date asc rows between 200 preceding and current row) as sma200, rsi_sma(close) over(partition by code order by trade_date asc rows between 14 preceding and current row) as rsi_sma_14 from cte_1) , cte_3 as ( select *, RANK() OVER (PARTITION BY code ORDER BY trade_date desc) AS rnk from cte_2 ) select distinct * from cte_3 where outlook = 'LONGTERM' and close < sma200 and rsi_sma_14 < 30 and pe < 22 order by trade_date desc"
# sql = "with cte_0 as ( select low,close,last,prevclose,no_trades,no_of_shrs,sc_name,net_turnov,sc_group,sc_type,tdcloindi,bhavcopy_file_name,sc_code,open,high from bhavcopy) select * from cte_0"
def index(request):
    # cur = conn.cursor()
    # cur.execute(sql)
    # rs = cur.fetchall()
    # print(rs[0])
   
    entities = Entity.objects.all()
    return render(request, 'radhatamapp/index.html', context={'entities': entities})


def dataingestion(request, action, id):
    data = {}
    entity = None
    fields = None
    entities = Entity.objects.all()
    if id:
        entity = Entity.objects.get(id=id)
        fields = Field.objects.filter(entity__id=id)
    if "GET" == request.method:        
        functions_calculated_meta = FunctionMeta.objects.filter(type='GENERATED')
        print(functions_calculated_meta)
        form = UploadFileForm()
        dataupload_form = UploadFileDataForm()
        entities_excluded = Entity.objects.exclude(id=id).all()
        print(entities_excluded)
        return render(request, "radhatamapp/dataingestion.html", context={'entities': entities,'form': form, 'entity': entity, 'entities': entities, 'fields': fields, 'dtypes': DATA_TYPES, 'dataupload_form': dataupload_form,'functions_calculated_meta':functions_calculated_meta,'entities_excluded':entities_excluded})
    # if not GET, then proceed
    if action == 'create':
        try:
            name = request.POST['name']
            csv_file = request.FILES["csv_file"]

            file_data = csv_file.read().decode("utf-8")
           
            cols = StringIO(file_data).readlines()[0].split(',')
      
            if id == 0:
                Entity.objects.filter(name=name).delete()
            entity = Entity.objects.create(name=name)
            entity.save()
            for col in cols:
                name = col.replace('.', '').replace(
                    '-', '_').replace("'", "").replace('"', '').replace(' ', '_').lower()
                Field.objects.create(
                    actual_name=col, name=name, entity=entity).save()
            # create an additinal file_name columnf
            Field.objects.create(
                actual_name=f'{entity.name}_file_name',
                name=f'{entity.name}_file_name', entity=entity).save()
            return HttpResponseRedirect(f'/dataingestion/display/{entity.id}')
        # return HttpResponseRedirect(reverse("radhatamapp:create_entity"))

        except Exception as e:
            logging.getLogger("error_logger").error(
                "Unable to upload file. "+repr(e))
            messages.error(request, "Unable to upload file. "+repr(e))
    
    if action == 'edit':
        if 'submit_action_delete' in request.POST:
            # if used in derived field then don't delete
            entity = Entity.objects.get(id=id)
            child_fields = Field.objects.filter(child_entity_id=entity.id)
            child_fields_entity_names = ','.join([c.entity.name for c in child_fields])
            child_fields_names = ','.join([c.name for c in child_fields])
            if len(child_fields) > 0:
                messages.error(request, f"This Entity is referenced in following Entity [{child_fields_entity_names}] with field [{child_fields_names}]")
            else:
                entity.delete()
                return HttpResponseRedirect(f'/')

    if action == 'add_calculated_field':
        derived_field_name = request.POST['derived_field_name']
        function_id = request.POST['function_id']
        

        function = FunctionMeta.objects.get(id=function_id)
        arguments_meta = ArgumentMeta.objects.filter(
            function__id=function_id)
        provided_argument = []
        for arg in arguments_meta:
            val = request.POST[arg.name]
            provided_argument.append(
                {"name": arg.name, "value": val, "type": arg.type})

        # argument_type = models.CharField(max_length=30, null=True)
        # create the derived field
        # field_level = get_level_of_fields(entity.id)
        derived_field = Field.objects.create(
            actual_name=derived_field_name, name=derived_field_name, entity=entity, type='CALCULATED', datatype=function.return_type, derived_level=0, function=function)
        derived_field.save()
        for parg in provided_argument:
            DerivedFieldArgument.objects.create(
                field=derived_field, argument_name=parg['name'], argument_value=parg['value'], argument_type=parg['type']).save()
        html = f'<span class="badge text-bg-primary">{function.name}</span>'
        return HttpResponse(html)

    if action == 'create_table':
        entity = Entity.objects.get(id=id)
        fields = Field.objects.filter(entity__id=id)
        sql = f"create table if not exists {entity.name}("

        for field in fields:
            if field.type == 'CALCULATED':
                function_meta = field.function
                derived_field_arguments = DerivedFieldArgument.objects.filter(
                    field=field.id)
                derived_values = {
                    d.argument_name: d.argument_value for d in derived_field_arguments}
                derived_values['name'] = field.name
                derived_function_sql = function_meta.return_sql.format(
                    **derived_values)

                sql += f"{field.name} {field.datatype} GENERATED ALWAYS AS ({derived_function_sql}) STORED,"
            elif field.type == 'DERIVED':
                pass
            else:
                sql += f"{field.name} {field.datatype},"

        # add created_at and refreshed_at
        sql += "created_at TIMESTAMP default now(),refreshed_at TIMESTAMP default now())"
        # sql = f"{sql[:-1]})"
        print(sql)
        execute_raw_query(f"drop table if exists {entity.name}")
        print(entity.name, ' DR')
        execute_raw_query(sql)
    if action == 'uploaddata':
        try:
            csv_files = request.FILES.getlist('csv_file')
            print(csv_files)

            entity = Entity.objects.get(id=id)
            fields = Field.objects.filter(entity__id=id)

            for csv_file in csv_files:
                print(csv_file)
                file_data = csv_file.read().decode("utf-8")
                file = StringIO(file_data).readlines()
                cols = file[0].split(',')
                print("============================================-")
                columns = []
                for col in cols:
                    name = replace_clean(col).lower()
                    columns.append(name)

                columns.append(f'{entity.name}_file_name')

                sql_cols = f"({(',').join(columns)})"
                for line in file[1:]:
                    # next(line)
                    vals = line.split(',')
                    field_sql = ''

                    for i, c in enumerate(vals):
                        if c.isdecimal() or c.isdigit() or c.isnumeric() or c.replace('.', '', 1).isdigit():
                            field_sql += f"{c},"
                        else:
                            c = c.replace("'", "")
                            field_sql += f"'{c}',"

                    field_sql = f"{field_sql}'{csv_file.name}'"
                    sql = f"insert into {entity.name} {sql_cols} values({field_sql})"
                    execute_raw_query(sql)
                    # break

            
        # return HttpResponseRedirect(reverse("radhatamapp:create_entity"))

        except Exception as e:
            logging.getLogger("error_logger").error(
                "Unable to upload file. "+repr(e))
            messages.error(request, "Unable to upload file. "+repr(e))
        return HttpResponseRedirect(f'/dataingestion/display/{id}')
    if action == 'add_child':
        print(request.POST)
        if request.POST['child_entity_id'] and not request.POST['child_field_id']:
            child_entity_name = request.POST['child_entity_id']

radhatam/radhatamapp/templates/radhatamapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@1.8.5"></script>
    
  <!-- <link
      rel="stylesheet"
      href="https://unpkg.com/papercss@1.9.2/dist/paper.min.css"
    /> -->
    <style>
        .first-color { 
	background: #e4f1fe; 
}
	
.second-color { 
	background: #8dc6ff; 
}

.third-color { 
	background: #22313f; 
}

.fourth-color { 
	background: #34495e; 
}
    </style>
</head>

<body>
    <header class="fourth-color"  style="color:white;padding:1em;border-bottom: 2px solid black;;">
    <h2 class="fourth-color" style="color:white;font-family:candara"><a style="color:white;" href="/" >rapidiam</a></h2>
    <em style="">Rapid Data Application with AI/ML Capabilities</em>
</header>
    <!-- <div class="htmx-indicator alert alert-success " role="alert">
        <img src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/AjaxLoader.gif" />
    </div> -->
      <div id="indicator"  class="htmx-indicator spinner-border" style="margin-left:50%;width: 3rem; height: 3rem; position:absolute;z-index: 2;" role="status">
        <span class="sr-only"></span>
      </div>
    <div class="row">
        <div class="col-2" style="background-color:#e4f1fe">
            <h6 style="border-bottom:1px solid darkgray;">Data Ingestion<a href="{% url 'radhatamapp:dataingestion' action='create' id=0 %}">[+]</a></h6>


            <table>

                {% for entity in entities%}
                <tr>
                    <td><a href="{% url 'radhatamapp:dataingestion' action='display' id=entity.id %}">{{entity}}</a>
                    </td>
                </tr>
                {% endfor %}


            </table>


            <h6 style="margin-top:1em;border-bottom:1px solid darkgray;">Data Preparation</h6>
            <table>

                {% for entity in entities%}
                <tr>
                    <td><a href="{% url 'radhatamapp:datapreparation' action='display' id=entity.id %}">{{entity}}</a></td>
                </tr>
                {% endfor %}


            </table>

       


            <h6 style="margin-top:1em;border-bottom:1px solid darkgray;">Data Visualization</h6>
            <table>

                {% for entity in entities%}
                <tr>
                    <td><a href="{% url 'radhatamapp:dataviz' action='display' id=entity.id %}">{{entity}}</a></td>
                </tr>
                {% endfor %}


            </table>

          
            <h6 style="margin-top:1em;border-bottom:1px solid darkgray;">Admin</h6>
            <table>
                <tr>
                    <td><a href="{% url 'radhatamapp:fieldfunction' action='display' id=0 %}">Field Fucntions</a></td>
                </tr>
            </table>

        </div>

        <div class="col-10">
            {% block content%}

            {% endblock %}
        </div>
    </div>
</body>

</html>

</html>
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>


<script>
    function closeForm(field_function_id) {
        document.getElementById(`edit_params_${field_function_id}`).innerHTML = "";
    }

</script>

radhatam/radhatamapp/templates/radhatamapp/dataingestion.html
{% extends 'radhatamapp/base.html'%}
{% block content %}
    <style>
            li.error{
        color:red;
    }
    </style>
    <!-- <img  src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/ajax-loader.gif"/> -->

    <h4 style="background-color: rgb(235, 250, 222);border:2px solid black;">Data Ingestion</h4>
    <h4>Create Data Entites with Computed Columns </h4>
   
   
   
    {% if not entity %}
    <form action="{% url 'radhatamapp:dataingestion' action='create' id=0%}" method="POST" class="post-form"
        enctype="multipart/form-data">
        {%csrf_token%}
        {{form}}
        <input type="submit" />
    </form>
    {% endif %}

    {% if entity %}

    <h4>{{entity}}
        <form method="POST" action="{% url 'radhatamapp:dataingestion' action='edit' id=entity.id %}">
            {% csrf_token %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
         <button class="btn btn-outline-danger" type="submit" name="submit_action_delete" value="Delete">X</button>
        </form>
        </h4>
   

    <table id="table">
        {% for field in fields %}
        <tr>
            {% if field.type == 'CALCULATED' %}
                <td><a href="{% url 'radhatamapp:fieldfunction' action='edit' id=field.function.id %}">[C]</a>{{field}}</td>
            {% elif field.type == 'DERIVED' %}
                <td><a href="{% url 'radhatamapp:fieldfunction' action='edit' id=field.function.id %}">[D]</a>{{field}}</td>
            {% else %}
                <td>[P]{{field}}</td>
            {% endif %}
            <td>
                <select hx-indicator="#indicator" hx-trigger="change" hx-swap="none" name="{{field.name}}"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    hx-post="{% url 'radhatamapp:edit_fieldtype' id=field.id %}">

                    {% for dtype in dtypes %}
                    <option {% if field.datatype == dtype.0 %} selected {% endif %} value={{dtype.0}}>
                        {{dtype.1}} </option>
                    {% endfor %}

                </select>
            </td>
        </tr>
        {% endfor %}

       
    </table>
    
   
    <form hx-indicator="#indicator" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    hx-post="{% url 'radhatamapp:dataingestion' action='add_calculated_field' id=entity.id %}">

    <span class="">Derived Field<a href="{% url 'radhatamapp:fieldfunction' action='createcalculated' id=0 %}">[+]</a></span>
    <input type="number" hidden name="level_field" value="{{level_field}}" />
    <select hx-indicator="#indicator" hx-trigger="change" name="function_id"
        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
        hx-post="{% url 'radhatamapp:datapreparation' action='get_function_params' id=entity.id %}"
        hx-target="#function-form">
        <option></option>
        {% for function in functions_calculated_meta %}

        <option value="{{function.id}}">{{function.name}}</option>
        {% endfor %}


    </select>
    <div id="function-form"></div>
    <!-- <a href="{% url 'radhatamapp:datapreparation' action='add_derived_column' id=entity.id %}">Add Derived Fields</a> -->
    <button type="submit">Add</button>
</form>
<tr><td><button hx-indicator="#indicator" hx-swap="none" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    hx-post="{% url 'radhatamapp:dataingestion' action='create_table' id=entity.id %}">Create Table </button></td></tr>

    {% endif %}

    <h4>Upload Data</h4>
    {% if entity %}



    <form action="{% url 'radhatamapp:dataingestion' action='uploaddata' id=entity.id%}" method="POST" class="post-form"
        enctype="multipart/form-data">
        {%csrf_token%}
        {{dataupload_form}}
        <input type="submit" />
    </form>
    {% endif %}

    <h4>Children</h4>
    {% for field in fields %}
    {{field}}
    {% endfor %}
   

    {% if entity %}


   <h4>Add Child</h4>
   <form hx-post="{% url 'radhatamapp:dataingestion' action='add_child' id=entity.id %}">
    {%csrf_token%}

    <select name="parent_field_id">
        <option></option>
        {% for field in fields %}
        <option value={{field.id}}>{{field.name}} </option>
        {% endfor %}
    </select>

    <select hx-target="#select-field" hx-indicator="#indicator" hx-trigger="change" name="child_entity_id"
        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
        hx-post="{% url 'radhatamapp:dataingestion' action='add_child' id=entity.id %}">
        <option></option>
        {% for entity in entities_excluded %}
        <option {% if entity.name == entity.child %} selected {% endif %} value={{entity.id}}>{{entity.name}} </option>
        {% endfor %}
    </select>

    <select id="select-field" name="child_field_id"></select>
    <button type="submit">Submit</button>
    
</form>

{% endif %}

{% endblock %}

radhatam/radhatamapp/templates/radhatamapp/index.html
{% extends 'radhatamapp/base.html'%}
{% block content %}
<main role="main">

    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading" style="font-family:candara">Rapidiam</h1>
        <p class="lead text-muted">Load You Data, Cleanse, Enrich, Apply Available Functions or build your own, Visualize and build Data Apps for fun and profit.</p>
        <!-- <p>
          <a href="#" class="btn btn-primary my-2">Documentation</a>
          <a href="https://www.youtube.com/@rebataurrebataur2166" target="_blank" class="btn btn-secondary my-2">Youtube Channel</a>
        </p> -->
        <iframe width="560" height="315" src="https://www.youtube.com/embed/NpEaa2P7qZI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      </div>
    </section>

  </main>
{% endblock %}